### ISSUE TITLE
Proposed ignored strings: paths and file / ftp protocols

### ISSUE THREAD

**Issue by Hibou57** [amandasaurus/python-pylint-i18n#3]
Hi,

I suggest to add strings looking like paths and ftp/file URLs too.

In `missing_gettext.py`, at line 87, changing this:

```
# URL, can't be translated
lambda x: x.startswith("http://") or x.endswith(".html"),
lambda x: x.startswith("https://") or x.endswith(".html"),
```

Into this:

```
# URL, can't be translated
lambda x: x.startswith("file://"),
lambda x: x.startswith("ftp://"),
lambda x: x.startswith("http://") or x.endswith(".html"),
lambda x: x.startswith("https://") or x.endswith(".html"),
lambda x: x.startswith("sftp://"),

# Paths, usually can't be translated
lambda x: x.startswith("~/"),
lambda x: x.startswith("$HOME/"),
lambda x: x.startswith("./") or x.endswith("/."),
lambda x: x.startswith("../") or x.endswith("/.."),
```

This would need to be Windows aware, but as I'm not running Windows since many years, I can't tell for sure what Python sources typically uses for the path separator: as Python for Windows handles `/` as if it was `\`, do Python program authors rather uses `/` or `\` in paths? I don't know…

About URI: may this would be better to check for URI testing conformance to the general URI format.

**Comment by amandasaurus** [comment]
That's a really good idea. Would you like to change the code and make a pull request? I'll get to it eventually, but if you do it could be faster.

**Comment by Hibou57** [comment]
OK. There's an easy way do to it, so this will be a tiny commit (I just have to check how to pull/commit using SVN, so be patient :-p ).

**Comment by Hibou57** [comment]
Sorry, It says “access not allowed”. I tried two times. I tried the SSH key password, my account password, my user name with all lower‑case or as‑is with title‑case, and it don't want me to commit.

**Comment by Hibou57** [comment]
I'm giving up. I tried all possible combination of SSH pass‑phrase, GitHub pass‑word, user name and e‑mail casing, with no avail: always “access denied”.

**Comment by amandasaurus** [comment]
:( I'm sorry you had that problems. Github has some advice here: https://help.github.com/articles/error-permission-denied-publickey

GIthub also allows you to work entirely inside the browser: https://help.github.com/articles/github-flow-in-the-browser Maybe you could try that.

I'll try to add your suggestions later today anyway.

**Comment by Hibou57** [comment]
Don't worry, I figured it all. I though I had to submit directly into your repository, thus the “access denied”. I've discovered I had to first fork, commit change to my fork, then propose a merge from my fork to yours.

**Comment by amandasaurus** [comment]
Yeah, took me a while to figure that github idiom out. :) I'll close this and continue discussion on pull request #5 .
