### ISSUE TITLE
Idea: discriminating between singled‑quoted and double‑quoted strings

### ISSUE THREAD

**Issue by Hibou57** [amandasaurus/python-pylint-i18n#4]
Hi,

I'm afraid that's not feasible, but that's still worth to be noticed: there is a convention among some people, to use double‑quotes around human readable strings, and single‑quotes around “code” / API strings.

Ex. `print("Hello!"`) vs `open(path, 'rb')`. The first which should be translatable, has double‑quotes, the second one, which is to not be translated, has single‑quotes.

**Comment by amandasaurus** [comment]
That's an interesting idea. I hadn't heard of that convention. I don't use it myself, but I think I will start!

I don't think it's well enough supported to make this code aware of it. For example I don't think [Django uses that style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/).

I'm not sure if it's possible to even _add_ this sort of "check for double quote/single quote" thing to this project. It might be.

**Comment by Hibou57** [comment]
Is there a standard function which could be used for this? Something which would act similarly to `r"regexp"` or `u"unicode"`, except in the form of a function. Or else, always doing something like this, which is recommended for good other reasons anyway:

```
# Special string constants definitions
# ====================================
# pylint: disable=W9903
CONST1 = 'foo'
CONST2 = 'bar'
# pylint: enable=W9903
```

I just wonder if there is something like `# pylint: restore=W9903` instead of `# pylint: enable=W9903`, to not enable it while it ever is disabled in PyLint's configuration.
